apiVersion: apps/v1
kind: Deployment
metadata:
  name: intellectaa-client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intellectaa-client
  template:
    metadata:
      labels:
        app: intellectaa-client
    spec:
      containers:
      - image: dilshadjr3312/intellectaa-client:latest
        name: intellectaa-client
        ports:
        - containerPort: 3000        
        volumeMounts:
        - mountPath: /app/.env.local
          name: env-local
          readOnly: true
          subPath: .env.local
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: .env
            path: .env.local
          name: env-local
        name: env-local
---
apiVersion: v1
kind: Service
metadata:
  name: intellectaa-client-srv
spec:
  selector:
    app: intellectaa-client
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer  